# nanodet-plus-m-1.5x_416
# COCO mAP(0.5:0.95) = 0.341
#             AP_50  = 0.506
#             AP_75  = 0.357
#           AP_small = 0.143
#               AP_m = 0.363
#               AP_l = 0.539
save_dir: ./temp/nanodet_plus_m_1.5x_416
check_point_name: plus_m_1.5x_416
model:
  weight_averager:
    name: ExpMovingAverager
    decay: 0.9998
  arch:
    name: NanoDetPlus
    detach_epoch: 10
    backbone:
      name: ShuffleNetV2
      model_size: 1.5x
      out_stages: [2,3,4]
      activation: LeakyReLU
    fpn:
      name: GhostPAN
      in_channels: [176, 352, 704]
      out_channels: 128
      kernel_size: 5
      num_extra_level: 1
      use_depthwise: True
      activation: LeakyReLU
    head:
      name: NanoDetPlusHead
      num_classes: 2
      input_channel: 128
      feat_channels: 128
      stacked_convs: 2
      kernel_size: 5
      strides: [8, 16, 32, 64]
      activation: LeakyReLU
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
    # Auxiliary head, only use in training time.
    aux_head:
      name: SimpleConvHead
      num_classes: 2
      input_channel: 256
      feat_channels: 256
      stacked_convs: 4
      strides: [8, 16, 32, 64]
      activation: LeakyReLU
      reg_max: 7
data:
  train:
    input_size: [640,640] #[w,h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
#      scale: [0.6, 1.4]
#      stretch: [[0.8, 1.2], [0.8, 1.2]]
#      rotation: 0
#      shear: 0
#      translate: 0.2
#      flip: 0.5
#      brightness: 0.2
#      contrast: [0.6, 1.4]
#      saturation: [0.5, 1.2]
#      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
      normalize: [[98.45438741, 104.10689567, 98.17277835], [34.79841708, 31.2228376, 29.66469302]]
  val:
    input_size: [640,640] #[w,h]
    keep_ratio: False
    pipeline:
#      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
      normalize: [[98.45438741, 104.10689567, 98.17277835], [34.79841708, 31.2228376, 29.66469302]]
device:
  gpu_ids: [0]
  workers_per_gpu: 8
  batchsize_per_gpu: 256
  precision: 32
schedule:
  resume: 0
  optimizer:
    name: SGD
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.05
  warmup:
    name: linear
    steps: 350
    ratio: 0.0001
  total_epochs: 100
  lr_schedule:
    name: CosineAnnealingLR
    T_max: 500
    eta_min: 0.00005
    last_epoch: -1
  val_intervals: 2
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP
log:
  interval: 1

class_names: ["poaceae", "brassicaceae"]