#Config File example
save_dir: ./temp/yolo_2
check_point_name: yolo_2
model:
  weight_averager:
    name: ExpMovingAverager
    decay: 0.9998
  arch:
    name: OneStageDetector
    backbone:
      name: Yolo
      arch: s
      activation: LeakyReLU
    fpn:
      name: Yolo
      arch: s
      kernel_size: 3
      upsample_cfg:
        scale_factor: 2
        mode: nearest
      activation: LeakyReLU
    head:
      name: Yolo
      num_classes: 2
      arch: s
      anchors:
        - [ 10,13, 16,30, 33,23 ]  # P3/8
        - [ 30,61, 62,45, 59,119 ]  # P4/16
        - [ 116,90, 156,198, 373,326 ]  # P5/32
      imgsz: 192
      inplace: True
      loss:
        cls_pw: 1.0  # cls BCELoss positive_weight
        obj_pw: 1.0  # obj BCELoss positive_weight
        label_smoothing: 0.0
        fl_gamma: 0.0  # focal loss gamma (efficientDet default gamma=1.5)
        box: 0.05  # box loss gain
        obj: 0.7  # obj loss gain (scale with pixels)
        cls: 0.3  # cls loss gain
data:
  train:
    input_size: [192, 192] #[w,h]
    keep_ratio: False
    cache_images: _
    pipeline:
      perspective: 0.0
      scale: [0.9, 1.1]
      stretch: [[0.9, 1.1], [0.9, 1.1]]
      rotation: 0
      shear: 0
      translate: 0.0
      flip: 0.5
      jitter_box: 0.1
      hard_pos: 0.0
      hard_pos_ratio: 0.0
      brightness: 0.2
      contrast: [0.8, 1.2]
      saturation: [0.8, 1.1]
      normalize: [[124.29, 122.21, 83.74], [50.3, 48.09, 51.71]]  # football
#      normalize: [[103.71, 108.77, 105.6], [31.51, 28.67, 27.91]]  # very small annots
#      normalize: [[98.45438741, 104.10689567, 98.17277835], [34.79841708, 31.2228376, 29.66469302]]  # full annots
  val:
    input_size: [192, 192] #[2456, 2054] #[640, 640] #[192, 192] #[96, 96] #[1920, 1088] #[w,h]
    keep_ratio: False
    cache_images: _
    pipeline:
      perspective: 0.0
      normalize: [[124.29, 122.21, 83.74], [50.3, 48.09, 51.71]]  # football
#      normalize: [[103.71, 108.77, 105.6], [31.51, 28.67, 27.91]]  # very small annots
#      normalize: [[98.45438741, 104.10689567, 98.17277835], [34.79841708, 31.2228376, 29.66469302]]  # full annots
  bench_test:
    input_size: [1248, 1056] #[1920, 1088] [2456, 2054]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      normalize: [[124.29, 122.21, 83.74], [50.3, 48.09, 51.71]]  # football
#      normalize: [[103.71, 108.77, 105.6], [31.51, 28.67, 27.91]]  # very small annots
#      normalize: [[98.45438741, 104.10689567, 98.17277835], [34.79841708, 31.2228376, 29.66469302]]  # full annots
device:
  gpu_ids: [0]
  workers_per_gpu: 1
  batchsize_per_gpu: 1
  precision: 32
schedule:
  resume: 0
  optimizer:
    name: AdamW
    lr: 0.001
    weight_decay: 0.05
  warmup:
    name: linear
    steps: 500
    ratio: 0.0001
  total_epochs: 300
  lr_schedule:
    name: CosineAnnealingWarmRestarts
    T_0: 10
    T_mult: 2
    eta_min: 0.00005
    last_epoch: -1
#    name: CosineAnnealingLR
#    T_max: 300
#    eta_min: 0.00005
  val_intervals: 1
  effective_batchsize: -1
grad_clip: 35
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP
log:
  interval: 10

class_names: ["poaceae", "brassicaceae"]
#class_names: ["player"]