#Config File example
save_dir: ./temp/plus_weight_averager_augmented_data_bigger_pos_with_augmentations_pre16_2
check_point_name: plus_weight_averager_augmented_data_bigger_pos_with_augmentations_pre16_2
model:
  weight_averager:
    name: ExpMovingAverager
    decay: 0.9998
  arch:
    name: OneStageDetector
    backbone:
      name: Vgg
      out_stages: [3, 4]
      stages_inplanes:  [3, 8, 8, 6]
      stages_outplanes: [8, 8, 6, 6]
      stages_strides:   [2, 2, 1, 2] #To fpn xriazete piramida me diafora scale 2 gia na litourgisi ara anamesa apo ta outs xrizete ena stride 2
      maxpool_kernels:  [0, 0, 0, 0]
      maxpool_strides:  [0, 0, 0, 0]
      activation: LeakyReLU
    fpn:
      name: GhostPAN #PAN #FPN  #PAN a litle slower than FPN
      in_channels: [6, 6] #[8, 8] #[8, 6]
      out_channels: 6
      upsample_cfg:
        scale_factor: 2
        mode: bilinear
      use_depthwise: True
      num_blocks: 1
      kernel_size: 3
      activation: LeakyReLU
    head:
      name: NanoDetPlusHead #NanoDetPlusHead NanoDetHead
      num_classes: 1
      input_channel: 6 #Out channel of fpn
      feat_channels: 6
      stacked_convs: 1 #Its pass in head have so many conv in list
      use_depthwise: True
#      octave_base_scale: 1 #Only in NanoDetHead
      kernel_size: 3 #Only in NanoDetPlusHead
      strides: [4, 8] #[4, 8] #[2, 4] #Set of last pass of all layers in head from the corresponding layer
      activation: LeakyReLU
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
data:
  train:
    input_size: [192, 192] #[w,h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      scale: [0.9, 1.1]
      stretch: [[0.9, 1.1], [0.9, 1.1]]
      rotation: 0
      shear: 0
      translate: 0.0
      flip: 0.5
      jitter_box: 0.1
      hard_pos: 0.0
      hard_pos_ratio: 0.0
      brightness: 0.2
      contrast: [0.6, 1.4]
      saturation: [0.5, 1.2]
      normalize: [[123.37, 120.76, 85.17], [53.46, 51.62, 53.99]]
  val:
    input_size: [192, 192] #[192, 192] #[96, 96] #[1920, 1088] #[w,h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      normalize: [[123.37, 120.76, 85.17], [53.46, 51.62, 53.99]]
  bench_test:
    input_size: [192, 192]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      normilize: [[123.37, 120.76, 85.17], [53.46, 51.62, 53.99]]
device:
  gpu_ids: [0]
  workers_per_gpu: 8
  batchsize_per_gpu: 256
  precision: 16
schedule:
  resume: 0
  optimizer:
    name: SGD
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.05
  warmup:
    name: linear
    steps: 1150
    ratio: 0.0001
  total_epochs: 600
  lr_schedule:
    name: CosineAnnealingLR
    T_max: 700
    eta_min: 0.00005
    last_epoch: -1
  val_intervals: 2
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP
log:
  interval: 10

class_names: ['player']