# NanoDet-g-416 is designed for edge NPU, GPU or TPU with high parallel computing power but low memory bandwidth
# COCO mAP(0.5:0.95) = 22.9
# Flops = 4.2B
# Params = 3.8M
# COCO pre-trained weight link: https://drive.google.com/file/d/10uW7oqZKw231l_tr4C1bJWkbCXgBf7av/view?usp=sharing
save_dir: ./temp/nanodet_g
check_point_name: g
model:
  arch:
    name: OneStageDetector
    backbone:
      name: CustomCspNet
      net_cfg: [[ 'Conv', 3, 32, 3, 2],  # 1/2
                [ 'MaxPool', 3, 2 ],  # 1/4
                [ 'CspBlock', 32, 1, 3, 1 ],  # 1/4
                [ 'CspBlock', 64, 2, 3, 2 ],  # 1/8
                [ 'CspBlock', 128, 2, 3, 2 ],  # 1/16
                [ 'CspBlock', 256, 3, 3, 2 ]]  # 1/32
      out_stages: [3,4,5]
      activation: LeakyReLU
    fpn:
      name: PAN
      in_channels: [128, 256, 512]
      out_channels: 128
      start_level: 0
      num_outs: 3
    head:
      name: NanoDetHead
      num_classes: 1
      conv_type: Conv
      activation: LeakyReLU
      input_channel: 128
      feat_channels: 128
      stacked_convs: 1
      share_cls_reg: True
      octave_base_scale: 8
      scales_per_octave: 1
      strides: [8, 16, 32]
      reg_max: 10
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
data:
  train:
    input_size: [91, 91] #[416,416] #[w,h]
    keep_ratio: True
    pipeline:
      perspective: 0.0
      scale: [0.6, 1.4]
      stretch: [[1, 1], [1, 1]]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [0.6, 1.4]
      saturation: [0.5, 1.2]
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
  val:
    input_size: [91, 91] #[w,h]  [2.65, 2.61]
    keep_ratio: True
    pipeline:
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
device:
  gpu_ids: [0]
  workers_per_gpu: 4
  batchsize_per_gpu: 1
  precision: 16
schedule:
  resume: 0
  optimizer:
    name: SGD
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.05
  warmup:
    name: linear
    steps: 350
    ratio: 0.0001
  total_epochs: 100
  lr_schedule:
    name: LinearLR
    start_factor: 1
    end_factor: 1
    total_iters: 1
    last_epoch: -1
    verbose: False
#    name: CosineAnnealingLR
#    T_max: 400
#    eta_min: 0.00005
#    last_epoch: -1
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP
log:
  interval: 10

class_names: ['wedd']
#class_names: ['player']
